---
version: "3.9"
services:
  clickhouse:
    networks:
      - clickhouse
    container_name: clickhouse-testing
    image: bitnami/clickhouse:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9009:9009
    volumes:
      - ./:/bitnami/clickhouse
networks:
  clickhouse: null