require "db"
require "protobuf"

module Clickhouse
  DBMS_MIN_REVISION_WITH_CLIENT_INFO                        = 54032
  DBMS_MIN_REVISION_WITH_SERVER_TIMEZONE                    = 54058
  DBMS_MIN_REVISION_WITH_QUOTA_KEY_IN_CLIENT_INFO           = 54060
  DBMS_MIN_REVISION_WITH_SERVER_DISPLAY_NAME                = 54372
  DBMS_MIN_REVISION_WITH_VERSION_PATCH                      = 54401
  DBMS_MIN_REVISION_WITH_CLIENT_WRITE_INFO                  = 54420
  DBMS_MIN_REVISION_WITH_SETTINGS_SERIALIZED_AS_STRINGS     = 54429
  DBMS_MIN_REVISION_WITH_INTERSERVER_SECRET                 = 54441
  DBMS_MIN_REVISION_WITH_OPENTELEMETRY                      = 54442
  DBMS_MIN_PROTOCOL_VERSION_WITH_DISTRIBUTED_DEPTH          = 54448
  DBMS_MIN_PROTOCOL_VERSION_WITH_INITIAL_QUERY_START_TIME   = 54449
  DBMS_MIN_PROTOCOL_VERSION_WITH_INCREMENTAL_PROFILE_EVENTS = 54451
  DBMS_MIN_REVISION_WITH_PARALLEL_REPLICAS                  = 54453
  DBMS_MIN_REVISION_WITH_CUSTOM_SERIALIZATION               = 54454
  DBMS_MIN_PROTOCOL_VERSION_WITH_ADDENDUM                   = 54458
  DBMS_MIN_PROTOCOL_VERSION_WITH_QUOTA_KEY                  = 54458
  DBMS_MIN_PROTOCOL_VERSION_WITH_PARAMETERS                 = 54459
  DBMS_TCP_PROTOCOL_VERSION                                 = DBMS_MIN_PROTOCOL_VERSION_WITH_PARAMETERS.to_u64
end

require "./clickhouse/*"
